default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: e_commerce_development

test:
  <<: *default
  database: e_commerce_test

production:
  primary:
    <<: *default
    database: e_commerce_production
  cache:
    <<: *default
    database: e_commerce_cache_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: e_commerce_queue_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: e_commerce_cable_production
    migrations_paths: db/cable_migrate
